dist: xenial
language: python
matrix:
  include:
    - name: "static analysis"
      python: "3.7"
      script:
        - black . --check --diff
        - python -m scanpy.tests.blackdiff 10
      after_success: skip
    - name: "anndata dev"
      python: "3.7"
      before_install:
          sudo apt-get update -qq
          sudo apt-get install -y r-base r-cran-matrix r-cran-rcppeigen r-cran-ggplot2
        - sudo Rscript -e "install.packages(\"sctransform\", repos=\"https://cran.rstudio.com\")"
      install:
        - pip install docutils sphinx
        - pip install -e .[test,louvain,leiden,magic,scvi,sctransform]
        # also test new umap. remove once umap 0.4+ is used by other runs as well
        - pip install umap-learn>=0.4 git+https://github.com/theislab/anndata
python:
  - '3.6'
  - '3.7'
  #- '3.8-dev' # https://github.com/numpy/numpy/issues/13790
cache:
  - pip
  - directories: data
before_install:
  - |
    sudo apt-get update -qq
    sudo apt-get install -y r-base r-cran-matrix r-cran-rcppeigen r-cran-ggplot2
  - sudo Rscript -e "install.packages(\"sctransform\", repos=\"https://cran.rstudio.com\")"
install:
  - pip install docutils sphinx
  - pip install -e .[test,louvain,leiden,magic,scvi,sctransform]
env:
  - MPLBACKEND=Agg
script:
  - pytest --ignore=scanpy/tests/_images
  - python setup.py check --restructuredtext --strict
  - rst2html.py --halt=2 README.rst >/dev/null
